# Run tests
name: contracts-confidential-token-wrappers-registry-tests

on:
  pull_request:

  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: ci-contracts-confidential-token-wrappers-registry-tests-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  check-changes:
    name: contracts-confidential-token-wrappers-registry-tests/check-changes
    permissions:
      actions: 'read' # Required to read workflow run information
      contents: 'read' # Required to checkout repository code
      pull-requests: 'read' # Required to read pull request information
    runs-on: ubuntu-latest
    outputs:
      changes-contracts-confidential-token-wrappers-registry: ${{ steps.filter.outputs.contracts-confidential-token-wrappers-registry }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        id: filter
        with:
          filters: |
            contracts-confidential-token-wrappers-registry:
              - .github/workflows/contracts-confidential-token-wrappers-registry-tests.yml
              - contracts/confidential-token-wrappers-registry/**
  tests:
    name: contracts-confidential-token-wrappers-registry-tests/tests (bpr)
    needs: check-changes
    if: ${{ needs.check-changes.outputs.changes-contracts-confidential-token-wrappers-registry == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read' # Required to checkout repository code
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'

      - name: Install dependencies
        working-directory: contracts/confidential-token-wrappers-registry
        run: npm ci

      - name: Run conformance
        working-directory: contracts/confidential-token-wrappers-registry
        run: make conformance

      - name: Run compile
        working-directory: contracts/confidential-token-wrappers-registry
        run: make compile

      - name: Run unit tests
        working-directory: contracts/confidential-token-wrappers-registry
        run: make test

